/**
 * KeyboardEvent Constants
 *
 * Mapping tables from fenster key indices to keyboard event key/code values.
 */

import {
	FENSTER_KEY_0,
	FENSTER_KEY_1,
	FENSTER_KEY_2,
	FENSTER_KEY_3,
	FENSTER_KEY_4,
	FENSTER_KEY_5,
	FENSTER_KEY_6,
	FENSTER_KEY_7,
	FENSTER_KEY_8,
	FENSTER_KEY_9,
	FENSTER_KEY_A,
	FENSTER_KEY_APOSTROPHE,
	FENSTER_KEY_B,
	FENSTER_KEY_BACKSLASH,
	FENSTER_KEY_BACKSPACE,
	FENSTER_KEY_BRACKET_LEFT,
	FENSTER_KEY_BRACKET_RIGHT,
	FENSTER_KEY_C,
	FENSTER_KEY_COMMA,
	FENSTER_KEY_D,
	FENSTER_KEY_DELETE,
	FENSTER_KEY_DOWN,
	FENSTER_KEY_E,
	FENSTER_KEY_END,
	FENSTER_KEY_EQUAL,
	FENSTER_KEY_ESCAPE,
	FENSTER_KEY_F,
	FENSTER_KEY_G,
	FENSTER_KEY_GRAVE,
	FENSTER_KEY_H,
	FENSTER_KEY_HOME,
	FENSTER_KEY_I,
	FENSTER_KEY_INSERT,
	FENSTER_KEY_J,
	FENSTER_KEY_K,
	FENSTER_KEY_L,
	FENSTER_KEY_LEFT,
	FENSTER_KEY_M,
	FENSTER_KEY_MINUS,
	FENSTER_KEY_N,
	FENSTER_KEY_O,
	FENSTER_KEY_P,
	FENSTER_KEY_PAGEDOWN,
	FENSTER_KEY_PAGEUP,
	FENSTER_KEY_PERIOD,
	FENSTER_KEY_Q,
	FENSTER_KEY_R,
	FENSTER_KEY_RETURN,
	FENSTER_KEY_RIGHT,
	FENSTER_KEY_S,
	FENSTER_KEY_SEMICOLON,
	FENSTER_KEY_SLASH,
	FENSTER_KEY_SPACE,
	FENSTER_KEY_T,
	FENSTER_KEY_TAB,
	FENSTER_KEY_U,
	FENSTER_KEY_UP,
	FENSTER_KEY_V,
	FENSTER_KEY_W,
	FENSTER_KEY_X,
	FENSTER_KEY_Y,
	FENSTER_KEY_Z,
} from "../Fenster";

// =============================================================================
// Physical key → `code` string
// =============================================================================

/** Maps fenster key index → KeyboardEvent code (physical key) */
export const FENSTER_TO_CODE: Record<number, string> = {
	// Navigation / control
	[FENSTER_KEY_BACKSPACE]: "Backspace",
	[FENSTER_KEY_TAB]: "Tab",
	[FENSTER_KEY_RETURN]: "Enter",
	[FENSTER_KEY_UP]: "ArrowUp",
	[FENSTER_KEY_DOWN]: "ArrowDown",
	[FENSTER_KEY_RIGHT]: "ArrowRight",
	[FENSTER_KEY_LEFT]: "ArrowLeft",
	[FENSTER_KEY_ESCAPE]: "Escape",
	[FENSTER_KEY_SPACE]: "Space",
	[FENSTER_KEY_DELETE]: "Delete",
	[FENSTER_KEY_HOME]: "Home",
	[FENSTER_KEY_PAGEUP]: "PageUp",
	[FENSTER_KEY_PAGEDOWN]: "PageDown",
	[FENSTER_KEY_END]: "End",
	[FENSTER_KEY_INSERT]: "Insert",

	// Letters (A-Z → KeyA-KeyZ)
	[FENSTER_KEY_A]: "KeyA",
	[FENSTER_KEY_B]: "KeyB",
	[FENSTER_KEY_C]: "KeyC",
	[FENSTER_KEY_D]: "KeyD",
	[FENSTER_KEY_E]: "KeyE",
	[FENSTER_KEY_F]: "KeyF",
	[FENSTER_KEY_G]: "KeyG",
	[FENSTER_KEY_H]: "KeyH",
	[FENSTER_KEY_I]: "KeyI",
	[FENSTER_KEY_J]: "KeyJ",
	[FENSTER_KEY_K]: "KeyK",
	[FENSTER_KEY_L]: "KeyL",
	[FENSTER_KEY_M]: "KeyM",
	[FENSTER_KEY_N]: "KeyN",
	[FENSTER_KEY_O]: "KeyO",
	[FENSTER_KEY_P]: "KeyP",
	[FENSTER_KEY_Q]: "KeyQ",
	[FENSTER_KEY_R]: "KeyR",
	[FENSTER_KEY_S]: "KeyS",
	[FENSTER_KEY_T]: "KeyT",
	[FENSTER_KEY_U]: "KeyU",
	[FENSTER_KEY_V]: "KeyV",
	[FENSTER_KEY_W]: "KeyW",
	[FENSTER_KEY_X]: "KeyX",
	[FENSTER_KEY_Y]: "KeyY",
	[FENSTER_KEY_Z]: "KeyZ",

	// Digits (0-9 → Digit0-Digit9)
	[FENSTER_KEY_0]: "Digit0",
	[FENSTER_KEY_1]: "Digit1",
	[FENSTER_KEY_2]: "Digit2",
	[FENSTER_KEY_3]: "Digit3",
	[FENSTER_KEY_4]: "Digit4",
	[FENSTER_KEY_5]: "Digit5",
	[FENSTER_KEY_6]: "Digit6",
	[FENSTER_KEY_7]: "Digit7",
	[FENSTER_KEY_8]: "Digit8",
	[FENSTER_KEY_9]: "Digit9",

	// Symbols
	[FENSTER_KEY_APOSTROPHE]: "Quote",
	[FENSTER_KEY_COMMA]: "Comma",
	[FENSTER_KEY_MINUS]: "Minus",
	[FENSTER_KEY_PERIOD]: "Period",
	[FENSTER_KEY_SLASH]: "Slash",
	[FENSTER_KEY_SEMICOLON]: "Semicolon",
	[FENSTER_KEY_EQUAL]: "Equal",
	[FENSTER_KEY_BRACKET_LEFT]: "BracketLeft",
	[FENSTER_KEY_BACKSLASH]: "Backslash",
	[FENSTER_KEY_BRACKET_RIGHT]: "BracketRight",
	[FENSTER_KEY_GRAVE]: "Backquote",
};

// =============================================================================
// Unshifted key → `key` string
// =============================================================================

/** Maps fenster key index → KeyboardEvent key (unshifted) */
export const FENSTER_TO_KEY: Record<number, string> = {
	// Navigation / control
	[FENSTER_KEY_BACKSPACE]: "Backspace",
	[FENSTER_KEY_TAB]: "Tab",
	[FENSTER_KEY_RETURN]: "Enter",
	[FENSTER_KEY_UP]: "ArrowUp",
	[FENSTER_KEY_DOWN]: "ArrowDown",
	[FENSTER_KEY_RIGHT]: "ArrowRight",
	[FENSTER_KEY_LEFT]: "ArrowLeft",
	[FENSTER_KEY_ESCAPE]: "Escape",
	[FENSTER_KEY_SPACE]: " ",
	[FENSTER_KEY_DELETE]: "Delete",
	[FENSTER_KEY_HOME]: "Home",
	[FENSTER_KEY_PAGEUP]: "PageUp",
	[FENSTER_KEY_PAGEDOWN]: "PageDown",
	[FENSTER_KEY_END]: "End",
	[FENSTER_KEY_INSERT]: "Insert",

	// Letters (A-Z → a-z lowercase)
	[FENSTER_KEY_A]: "a",
	[FENSTER_KEY_B]: "b",
	[FENSTER_KEY_C]: "c",
	[FENSTER_KEY_D]: "d",
	[FENSTER_KEY_E]: "e",
	[FENSTER_KEY_F]: "f",
	[FENSTER_KEY_G]: "g",
	[FENSTER_KEY_H]: "h",
	[FENSTER_KEY_I]: "i",
	[FENSTER_KEY_J]: "j",
	[FENSTER_KEY_K]: "k",
	[FENSTER_KEY_L]: "l",
	[FENSTER_KEY_M]: "m",
	[FENSTER_KEY_N]: "n",
	[FENSTER_KEY_O]: "o",
	[FENSTER_KEY_P]: "p",
	[FENSTER_KEY_Q]: "q",
	[FENSTER_KEY_R]: "r",
	[FENSTER_KEY_S]: "s",
	[FENSTER_KEY_T]: "t",
	[FENSTER_KEY_U]: "u",
	[FENSTER_KEY_V]: "v",
	[FENSTER_KEY_W]: "w",
	[FENSTER_KEY_X]: "x",
	[FENSTER_KEY_Y]: "y",
	[FENSTER_KEY_Z]: "z",

	// Digits (0-9)
	[FENSTER_KEY_0]: "0",
	[FENSTER_KEY_1]: "1",
	[FENSTER_KEY_2]: "2",
	[FENSTER_KEY_3]: "3",
	[FENSTER_KEY_4]: "4",
	[FENSTER_KEY_5]: "5",
	[FENSTER_KEY_6]: "6",
	[FENSTER_KEY_7]: "7",
	[FENSTER_KEY_8]: "8",
	[FENSTER_KEY_9]: "9",

	// Symbols (unshifted)
	[FENSTER_KEY_APOSTROPHE]: "'",
	[FENSTER_KEY_COMMA]: ",",
	[FENSTER_KEY_MINUS]: "-",
	[FENSTER_KEY_PERIOD]: ".",
	[FENSTER_KEY_SLASH]: "/",
	[FENSTER_KEY_SEMICOLON]: ";",
	[FENSTER_KEY_EQUAL]: "=",
	[FENSTER_KEY_BRACKET_LEFT]: "[",
	[FENSTER_KEY_BACKSLASH]: "\\",
	[FENSTER_KEY_BRACKET_RIGHT]: "]",
	[FENSTER_KEY_GRAVE]: "`",
};

// =============================================================================
// Shifted key → `key` string (only entries that differ from unshifted)
// =============================================================================

/** Maps fenster key index → KeyboardEvent key when shift is held */
export const SHIFTED_KEY: Record<number, string> = {
	// Letters (a-z → A-Z)
	[FENSTER_KEY_A]: "A",
	[FENSTER_KEY_B]: "B",
	[FENSTER_KEY_C]: "C",
	[FENSTER_KEY_D]: "D",
	[FENSTER_KEY_E]: "E",
	[FENSTER_KEY_F]: "F",
	[FENSTER_KEY_G]: "G",
	[FENSTER_KEY_H]: "H",
	[FENSTER_KEY_I]: "I",
	[FENSTER_KEY_J]: "J",
	[FENSTER_KEY_K]: "K",
	[FENSTER_KEY_L]: "L",
	[FENSTER_KEY_M]: "M",
	[FENSTER_KEY_N]: "N",
	[FENSTER_KEY_O]: "O",
	[FENSTER_KEY_P]: "P",
	[FENSTER_KEY_Q]: "Q",
	[FENSTER_KEY_R]: "R",
	[FENSTER_KEY_S]: "S",
	[FENSTER_KEY_T]: "T",
	[FENSTER_KEY_U]: "U",
	[FENSTER_KEY_V]: "V",
	[FENSTER_KEY_W]: "W",
	[FENSTER_KEY_X]: "X",
	[FENSTER_KEY_Y]: "Y",
	[FENSTER_KEY_Z]: "Z",

	// Digits (0-9 → shifted symbols)
	[FENSTER_KEY_0]: ")",
	[FENSTER_KEY_1]: "!",
	[FENSTER_KEY_2]: "@",
	[FENSTER_KEY_3]: "#",
	[FENSTER_KEY_4]: "$",
	[FENSTER_KEY_5]: "%",
	[FENSTER_KEY_6]: "^",
	[FENSTER_KEY_7]: "&",
	[FENSTER_KEY_8]: "*",
	[FENSTER_KEY_9]: "(",

	// Symbols (shifted)
	[FENSTER_KEY_APOSTROPHE]: '"',
	[FENSTER_KEY_COMMA]: "<",
	[FENSTER_KEY_MINUS]: "_",
	[FENSTER_KEY_PERIOD]: ">",
	[FENSTER_KEY_SLASH]: "?",
	[FENSTER_KEY_SEMICOLON]: ":",
	[FENSTER_KEY_EQUAL]: "+",
	[FENSTER_KEY_BRACKET_LEFT]: "{",
	[FENSTER_KEY_BACKSLASH]: "|",
	[FENSTER_KEY_BRACKET_RIGHT]: "}",
	[FENSTER_KEY_GRAVE]: "~",
};
